name: Production CI

on:
    push:
        branches: [main] # Runs every time you push to main
    pull_request:
        branches: [main] # Runs every time you open a PR

jobs:
    quality-gate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install Dependencies
              run: npm install # 'BUT npm ci' is better for CI than 'npm install'

            - name: Lint Check
              run: npm run lint
              continue-on-error: false # Fails the pipeline if code is messy

            - name: Test Build
              run: npm run build # Ensures the project actually builds

    docker-build:
        needs: quality-gate # Only runs if the checks above pass!
        runs-on: ubuntu-latest
        env: 
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker Image
              run: |
                  docker build -t my-portfolio:${{ github.sha }} .
                  echo "Docker build successful!"
